travis:
  secure:
    BINSTAR_TOKEN: Wx1jI6XPCU7wmyTanENrDzIXsnS/fILPbtlqp3iPpsNfs4OGb0JYiGzemDE56rTbAeQIk09UuxWzoUctTzjSSZ1fDSjjsTW1LSpMWbTpJw8gRwukfxZh19U/rd8S/P0IxcIW+Gd6W+dq9oQpyt5NnGLPVIxgfCrclx/c+knd+PsyIBXADfYg+RFrG6opUzNpAejvZT1YhG0y1ZrHjnRCyGENKY1m4O3PEs/xDJGUeEJQH8aDBRPV5UrTLL5L1GU39B3Im8MpXpPZdpkr96/BH7BYJ4X11rCeAJOyC+ue83xm38VyCPFfuMHRv7Zbg+JIb5XCFwla9ZlxQ9AZiD6P7/p/GXnMLIVVnCCuGB+kvwFACsaIwfgHSndjVraeKRK3WRfMqJ/q+NOFgSScfhUcCX3XXOkPmpZ02IYJsydfr5iIHXcOxH6wWyM4ixdfVPPg7lVUkmpdaRZFRh+D+QzsnvFgWCFpDIxu0gzqUWqMmAEybEWx6iarW8gzbUNq/aCE1mymVDm71tRSAmhJa8HPZFwf3aeRJDA+ezuhzAl/9N6tnPykoZ3IjF0ekaGwwzTx/r9NyVuonfCYXIts4OX/6ejdKQ4GiHG5d+aUwbHc6PKNUh/lHqeOzdk1XfN/lXfI+Y6GxG87t90FXIHPO31bgkl+sgjDX6wYgkxDAdRdrUk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
